-- LABORATORY 4 - ROLE-BASED ASSET TRANSACTION AND APPROVAL MANAGEMENT
-- Run this in Supabase SQL Editor.

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'User',
  role text not null default 'requester' check (role in ('admin','staff','requester')),
  created_at timestamptz not null default now()
);

create table if not exists equipment (
  id bigint generated by default as identity primary key,
  asset_code text unique not null,
  name text not null,
  category text not null,
  description text,
  status text not null default 'Available'
    check (status in ('Available','Borrowed','Maintenance')),
  created_at timestamptz not null default now()
);

create table if not exists borrowing_requests (
  id bigint generated by default as identity primary key,
  equipment_id bigint not null references equipment(id),
  requester_id uuid not null references auth.users(id),
  requester_name text not null,
  purpose text not null,
  date_requested timestamptz not null default now(),
  expected_return date,
  actual_return date,
  status text not null default 'Pending'
    check (status in ('Pending','Approved','Rejected','Released','Returned','Overdue','Closed')),
  damage_report text,
  approved_by uuid references auth.users(id),
  released_at timestamptz,
  returned_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists maintenance_requests (
  id bigint generated by default as identity primary key,
  equipment_id bigint not null references equipment(id),
  submitted_by uuid not null references auth.users(id),
  description text not null,
  status text not null default 'Pending' check (status in ('Pending','In Progress','Completed')),
  created_at timestamptz not null default now()
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  action text not null,
  module text not null,
  record_id bigint,
  description text not null,
  created_at timestamptz not null default now()
);

-- Keep Lab 3 service requests available as the existing system module.
-- If your Lab 3 table already exists, this statement does nothing.
create table if not exists service_requests (
  id bigint generated by default as identity primary key,
  requester_name text not null,
  department text not null,
  category text not null,
  description text not null,
  priority text not null check (priority in ('Low','Medium','High')),
  status text not null default 'Pending' check (status in ('Pending','In Progress','Completed')),
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id)
);

-- Profile creation trigger for new Auth users.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(coalesce(new.email,'User'),'@',1)),
    case when new.raw_user_meta_data->>'role' in ('admin','staff','requester')
         then new.raw_user_meta_data->>'role' else 'requester' end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Helper functions make database authorization enforceable without exposing all profiles.
create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.is_staff_or_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role in ('staff','admin'));
$$;

grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_staff_or_admin() to authenticated;

-- RLS
alter table profiles enable row level security;
alter table equipment enable row level security;
alter table borrowing_requests enable row level security;
alter table maintenance_requests enable row level security;
alter table audit_logs enable row level security;
alter table service_requests enable row level security;

-- Re-runnable policy cleanup.
do $$
declare p record;
begin
  for p in select schemaname, tablename, policyname from pg_policies
           where schemaname='public' and tablename in ('profiles','equipment','borrowing_requests','maintenance_requests','audit_logs','service_requests')
  loop execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename); end loop;
end $$;

create policy profiles_select_own on profiles for select to authenticated using (id = auth.uid() or public.is_admin());
create policy profiles_admin_all on profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy equipment_view on equipment for select to authenticated using (true);
create policy equipment_admin_insert on equipment for insert to authenticated with check (public.is_admin());
create policy equipment_admin_update on equipment for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy equipment_admin_delete on equipment for delete to authenticated using (public.is_admin());

create policy borrowing_view on borrowing_requests for select to authenticated
using (requester_id = auth.uid() or public.is_staff_or_admin());
create policy borrowing_insert on borrowing_requests for insert to authenticated
with check (requester_id = auth.uid() and status = 'Pending');
create policy borrowing_staff_update on borrowing_requests for update to authenticated
using (public.is_staff_or_admin()) with check (public.is_staff_or_admin());
create policy borrowing_admin_delete on borrowing_requests for delete to authenticated
using (public.is_admin());

create policy maintenance_view on maintenance_requests for select to authenticated
using (submitted_by = auth.uid() or public.is_staff_or_admin());
create policy maintenance_insert on maintenance_requests for insert to authenticated
with check (submitted_by = auth.uid());
create policy maintenance_staff_update on maintenance_requests for update to authenticated
using (public.is_staff_or_admin()) with check (public.is_staff_or_admin());

create policy audit_admin_view on audit_logs for select to authenticated using (public.is_admin());
create policy audit_authenticated_insert on audit_logs for insert to authenticated with check (user_id = auth.uid());

create policy service_view on service_requests for select to authenticated using (true);
create policy service_insert on service_requests for insert to authenticated with check (user_id = auth.uid());
create policy service_update_own on service_requests for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy service_delete_own on service_requests for delete to authenticated using (user_id = auth.uid());

-- Sample equipment. Safe to run more than once because asset_code is unique.
insert into equipment (asset_code,name,category,description,status) values
('LAP-001','Dell Latitude Laptop','Laptop','Laboratory laptop for academic activities','Available'),
('LAP-002','Lenovo ThinkPad Laptop','Laptop','Laptop for programming and documentation','Available'),
('PROJ-001','Epson Projector','Projector','Multimedia projector for presentations','Available'),
('MON-001','Dell 24-inch Monitor','Monitor','External monitor for laboratory workstation','Available'),
('PRN-001','HP Laser Printer','Printer','Black and white laboratory printer','Maintenance')
on conflict (asset_code) do nothing;

-- IMPORTANT: After creating your test users in Authentication, assign roles using their UUIDs.
-- Example:
update profiles set role='admin', full_name='Junry Pacot' where id='abc8aef4-38af-4146-b754-7e897e3bb52b';
update profiles set role='staff', full_name='Ana Garcia' where id='7700fcc4-c2b2-4ff5-bc2d-32ddc29a3bd2';
update profiles set role='requester', full_name='Maria Santos' where id='bcd5f4ef-8e6f-4b2c-9add-a832805b5b55';
